### ISSUE TITLE
Destination Host Unreachable (Cannot ping)

### ISSUE THREAD

**Issue by dolbo** [frenetic-lang/frenetic#157]
Hi, everyone. I'm looking for some help. 
I'm going through the Tutorial. I'd like to make simple experiment which is described in Chapter 6. I follow the instruction: 

I downloaded frenetic - import in VMplayer start my Mininet 

update opam 
upgrade opam

mininet> sudo mn --controller=remote

I start    frenetic Repeater.nc

and I cannot ping mininet> h1 ping -c3 h2  Destination host ist unrecheable.

I also try others experiment and I cannot ping host. I'm a bit confused about that How can i solve my problem ? I assume that i forgot to do something but I follow the instruction in tutorial.

**Comment by craig-riecke** [comment]
This was fixed awhile ago, so closing.

**Comment by harishphn** [comment]
I still see this issue. 

I started mininet: sudo mn --topo=single,2 --controller=remote

and ran the repeater application: python -m frenetic.examples.repeater

I am not able to reach h2 from h1 as it says Destination Host Unreachable. It was working fine for some time and suddenly I started getting this issue
